# ===== anchors =====
x-common: &common
  build: &common-build
    context: ../..
    dockerfile: src/config/.dockerfile
  env_file:
    - ../../.env
  environment:
    PYTHONUNBUFFERED: "1"
  restart: unless-stopped
  networks: [backend]
  working_dir: /app
  volumes:
    - ../app:/app
    - ../data:/app/data

# ===== networks/volumes =====
networks:
  backend:

volumes:
  hf_cache:

services:

  # ---------- UI ----------
  streamlit:
    <<: *common
    build:
      <<: *common-build
      target: streamlit
    command: streamlit run web.py --server.port 8501 --server.address 0.0.0.0
    ports: ["8501:8501"]
    # streamlit дергает main по имени сервиса
    environment:
      FASTAPI_HOST: main
    depends_on:
      - main
  # ---------- main ----------
  main:
    build:
      <<: *common-build
      target: main
    <<: *common
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

    ports: ["8000:8000"] 

  # ---------- internal microservices ----------
  server:
    build:
      <<: *common-build
      target: server
    <<: *common
    command: uvicorn server:app --reload --host 0.0.0.0 --port 5002
    ports: ["5002:5002"] 

  vector_db:
    <<: *common
    build:
      <<: *common-build
      target: vector_db
    command: uvicorn vector_db:app --reload --host 0.0.0.0 --port 5004
    volumes:
      - ../app:/app
      - hf_cache:/root/.cache/huggingface
    ports: ["5004:5004"] 
    healthcheck:
      test: [ "CMD-SHELL", "if [ -f /tmp/healthy_vector_db ]; then exit 0; else curl -f http://localhost:5004/health && touch /tmp/healthy_vector_db; fi" ]
      interval: 2s
      timeout: 10s
      retries: 10000

  mongo:
    <<: *common
    build:
      <<: *common-build
      target: mongo
    command: uvicorn mongo:app --reload --host 0.0.0.0 --port 5017
    ports: ["5017:5017"] 
    volumes:
      - ../app:/app
      - hf_cache:/root/.cache/huggingface

  question_model:
    <<: *common
    build:
      <<: *common-build
      target: question_model

    command: uvicorn question_model:app --reload --host 0.0.0.0 --port 5005
    ports: ["5005:5005"] 
    volumes:
      - ../app:/app
      - hf_cache:/root/.cache/huggingface
    healthcheck:
      test: [ "CMD-SHELL", "if [ -f /tmp/healthy ]; then exit 0; else curl -f http://localhost:5005/health && touch /tmp/healthy; fi" ]
      # проверяет только первый раз 
      interval: 2s
      timeout: 10s
      retries: 10000
  notifier:
    image: alpine
    depends_on:
      question_model:
        condition: service_healthy
      vector_db:
        condition: service_healthy
    command: [ "sh", "-c", "echo '✅ Все сервисы готовы'" ]
